---

- hosts: homesync
  tasks:
    # write files
    - name: write .z-bash-env
      copy: src={{ item }} dest=~/.z-bash-env
      with_first_found:
        - ~/.z-bash-env.{{ homesync_env }}
        - ~/.z-bash-env.homesync
        - ~/.z-bash-env

    - name: write .z-bash-aliases
      copy: src={{ item }} dest=~/.z-bash-aliases
      with_first_found:
        - ~/.z-bash-aliases.{{ homesync_env }}
        - ~/.z-bash-aliases.homesync
        - ~/.z-bash-aliases

    - name: write .z-bash-functions
      copy: src={{ item }} dest=~/.z-bash-functions
      with_first_found:
        - ~/.z-bash-functions.{{ homesync_env }}
        - ~/.z-bash-functions.homesync
        - ~/.z-bash-functions

    - name: write .z-bash-prompt
      copy: src={{ item }} dest=~/.z-bash-prompt
      with_first_found:
        - ~/.z-bash-prompt.{{ homesync_env }}
        - ~/.z-bash-prompt.homesync
        - ~/.z-bash-prompt

    - name: write .z-bashrc
      copy: src={{ item }} dest=~/.z-bashrc
      with_first_found:
        - ~/.z-bashrc.{{ homesync_env }}
        - ~/.z-bashrc.homesync
        - ~/.z-bashrc

    # setup .bashrc
    - name: remove old .bashrc settings
      lineinfile: >
        dest=~/.bashrc
        regexp="COLOR_USER=|COLOR_HOST=|\. ~\/.z-bashrc"
        state=absent

    - name: source .z-bashrc from .bashrc
      lineinfile: >
        dest=~/.bashrc
        regexp="~\/\.z-bashrc"
        line="source ~/.z-bashrc"

    # cleanup
    - name: remove bin if empty
      command: rmdir ~/bin
      failed_when: false
      changed_when: false
